# proxy.yaml

basepath: "/v1/hipster"
operations:
- id: products
  http_match:
  - path_template: "/products"
    method: GET
- id: product-detail
  http_match:
  - path_template: "/products/*"
    method: GET

target:
  target_server_id: products

