
name: Apigee Configurable Proxy CI 

on: push
  
env:
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_CONFIG_ENV: configurable-dev
  TEST_HOST: 34-117-38-184.nip.io

jobs:
  Apigee-Deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create Dependencies (npm) Cache 
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` 
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-


      # Install dependencies (npm)
      - name: Install Dependencies
        run: npm install --silent --no-fund
      

      # google-github-actions: Authenticate against Google Cloud with Service Account (Secret) 
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      # google-github-actions: Install and configure gcloud (alpha for Apigee commands)
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          install_components: 'alpha'

#      - name: 'Use gcloud CLI'
#        run: 'gcloud info'

      # Deploy Configurable Proxy
      - name: 'deploy configurable proxy'
        run: |
          mv ./proxy/src/main/apigee/environments/ENVIRONMENT-NAME ./proxy/src/main/apigee/environments/$APIGEE_CONFIG_ENV
          gcloud alpha apigee archives deploy --organization=$APIGEE_ORG --environment=$APIGEE_CONFIG_ENV --source=proxy


      # Run Integration testing (Apickli) + upload artifact (cucumber_report.html)
      - name: apickli
        run: |
          # extract basepath from proxy config file
          API_BASEPATH=$(grep 'basepath:' ./proxy/src/main/apigee/apiproxies/hipster-conf/config.yaml | tail -n1 | awk '{ print $2}' | sed 's,/,\\/,g' | tr -d '"')
          
          # extract proxy name from folder structure
          PROXY-NAME=$(ls ./proxy/src/main/apigee/apiproxies/)

          # update apickli config file (init.js) with API hostname and base path
          sed -i "s/api_basepath/$API_BASEPATH/g" ./test/$PROXY-NAME/integration/features/support/init.js
          sed -i "s/organization_hostname/$TEST_HOST/g" ./test/$PROXY-NAME/integration/features/support/init.js

          # NODE_TLS_REJECT_UNAUTHORIZED required to support self signed certificate
          export NODE_TLS_REJECT_UNAUTHORIZED=0

          node ./node_modules/.bin/cucumber-js  ./test/$PROXY-NAME/integration --format json:./report.json
          node ./test/index.js

      - name: Archive Apickli results
        uses: actions/upload-artifact@v2
        with:
          name: apickli-report
          path: ./cucumber_report.html
          retention-days: 5
